user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    server {
        listen 80;

        location /admin/ {
            proxy_pass https://project-management-backend-maqwzj67wq-as.a.run.app/admin/;
            proxy_ssl_server_name on;
            proxy_set_header Host project-management-backend-maqwzj67wq-as.a.run.app;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            proxy_pass https://project-management-backend-maqwzj67wq-as.a.run.app/static/;
            proxy_ssl_server_name on;
        }


        location / {
            proxy_pass https://ksc-nextjs-maqwzj67wq-as.a.run.app/;
            proxy_ssl_server_name on;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host ksc-nextjs-maqwzj67wq-as.a.run.app;
            proxy_cache_bypass $http_upgrade;
        }
    }

}
