# Generated by Django 3.2.1 on 2025-12-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='company',
            new_name='vendor',
        ),
    ]
