# Generated by Django 3.2.1 on 2025-12-16 08:30

import apps.persons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20251216_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondocument',
            name='file',
            field=models.FileField(upload_to=apps.persons.models.document_upload_to),
        ),
    ]
