# Generated by Django 3.2.1 on 2026-02-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_vendordocument_file'),
        ('persons', '0004_alter_persondocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='person',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='vendors.vendor'),
        ),
    ]
