# Generated by Django 3.2.1 on 2025-12-16 03:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('npwp', models.CharField(max_length=50, unique=True)),
                ('company_type', models.CharField(choices=[('PT', 'PT'), ('CV', 'CV'), ('BUMN', 'BUMN'), ('PERSONAL', 'Perorangan')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
