# Generated by Django 3.2.1 on 2025-12-16 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Vendors',
        ),
    ]
