# Generated by Django 3.2.1 on 2025-12-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_rename_company_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='address',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='npwp',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
