# Generated by Django 3.2.1 on 2025-12-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_vendors_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='company_type',
            new_name='vendor_type',
        ),
    ]
