# Generated by Django 3.2.1 on 2025-12-16 06:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_rename_company_type_vendor_vendor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('npwp', 'npwp'), ('portfolio', 'portfolio')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='vendors/documents/')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
