# Generated by Django 3.2.1 on 2025-12-16 08:30

import apps.vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendordocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordocument',
            name='file',
            field=models.FileField(upload_to=apps.vendors.models.document_upload_to),
        ),
    ]
