# Generated by Django 3.2.1 on 2025-12-16 04:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0003_auto_20251216_1054'),
        ('projects', '0001_initial'),
        ('vendors', '0005_rename_company_type_vendor_vendor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement_type', models.CharField(choices=[('lelang', 'Lelang'), ('penunjukan', 'Penunjukan Langsung')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('evaluation', 'Evaluation'), ('winner_selected', 'Winner Selected'), ('failed', 'Failed')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurements', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('submission_date', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('evaluated', 'Evaluated'), ('winner', 'Winner'), ('loser', 'Loser')], max_length=20)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='procurements.procurement')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'unique_together': {('procurement', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='procurements.procurementparticipant')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
