# Generated by Django 3.2.1 on 2025-12-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcurementPersonnel',
        ),
    ]
