# Generated by Django 3.2.1 on 2025-12-16 08:56

import apps.procurements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurements', '0003_procurementparticipant_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementparticipant',
            name='file',
            field=models.FileField(null=True, upload_to=apps.procurements.models.document_upload_to),
        ),
    ]
