# Generated by Django 4.2.28 on 2026-03-02 03:38

import apps.inventaris.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenagaAhli',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_lengkap', models.CharField(max_length=255, unique=True)),
                ('jabatan', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('telepon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenagaAhliDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('cv', 'CV'), ('sertifikat', 'sertifikat'), ('lainnya', 'lainnya')], max_length=20)),
                ('judul', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.inventaris.models.document_upload_to)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventaris.tenagaahli')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
